name: CI/CD NexTraceWeb Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Start preview server
        run: npm run preview &
        env:
          CI: true

      - name: Wait for preview
        run: npx wait-on http://localhost:5173

      - name: Run Cypress E2E
        run: npx cypress run
